tests/test_triangle.py, vsketch/vsketch.py
Added triangle() primitive and tests
=> Feature triangle

tests/test_square.py, vsketch/vsketch.py
Add feature square()
- [ x ] feature/fix implemented
- [ x ] `mypy vsketch tests` returns no error
- [ x ] tests added/updated and all tests succeed
- [ x ] documentation added/updated
- [ x ] examples added/updated and freshly executed in jupyter ("Reload kernel and run all cells")
- [ x ] code formating ok (`black` and `isort`)
=> Feature square

examples/vsketch_google_colab_basic_setup.ipynb
Added a Google Colab notebook to the examples for easier setup & use in-browser.
=> Google Colab notebook example

.github/pull_request_template.md, .github/workflows/python-tests.yml, README.rst, examples/google_colab.ipynb, examples/prime_circles.ipynb, requirements.txt, tests/conftest.py, tests/test_examples.py, vsketch/vsketch.py
- rename pipeline() to vpype()
- add proper documentation
- automate testing of all notebooks
=> Improve/rename `vpype()` (was `pipeline()`)

tests/test_arc.py, vsketch/utils.py, vsketch/vsketch.py
Added feature arc() and tests.
=> Feature arc

examples/subsketch.ipynb, tests/test_rect.py, tests/test_square.py, vsketch/vsketch.py
=> Feature round corners

tests/test_save.py, vsketch/vsketch.py
=> Add support for HPGL export

tests/test_transforms.py, vsketch/utils.py, vsketch/vsketch.py
=> resetMatrix() as a context manager

tests/test_curves.py, tests/test_detail.py, tests/test_stroke.py, tests/utils.py, vsketch/curves.py, vsketch/display.py, vsketch/vsketch.py
see abey79/vpype#97 and abey79/vpype#98
=> Adjust to recent changes in vpype ('Document' and 'page_size')

.github/pull_request_template.md, .gitignore, examples/bezier_bugs/sketch_bezier_bugs.py, examples/detail/sketch_detail.py, examples/noise_bezier/sketch_noise_bezier.py, examples/prime_circles/sketch_prime_circles.py, examples/quick_draw/sketch_quick_draw.py, examples/random_flower/sketch_random_flower.py, examples/random_lines/sketch_random_lines.py, examples/schotter/sketch_schotter.py, poetry.lock, tests/test_examples.py, tests/utils.py, vsketch/param.py, vsketch_cli/cli.py
Converted Param to use descriptor protocol.
The the process, the following addition were needed:
- Added --destination to vsk save
- Updated all examples
- Added a test to run all examples
- vsk commands now have exit status of 1 on error condition
=> Use descriptor protocol for Param

tests/test_misc.py, vsketch/vsketch.py
=> Feature: add `lerp()` function

docs/overview.rst
=> Doc: changed call to pushMatrix() to vsk.pushMatrix()

README.md
PR to improve installation instructions as highlighted in Issue#136
...
- [ ^] documentation added/updated and building with no error (`make clean && make html` in `docs/`)
=> added Python 3.7x requirement

poetry.lock, pyproject.toml, tests/test_geometry.py, vsketch/vsketch.py, vsketch_cli/utils.py
- `vsk.geometry()` now handles GeometryCollection objects
- updated deps
- fixed a mypy error
=> Fix issue where GeometryCollection objects were not recognised by `vsk.geometry()`

examples/_notebooks/README.md, poetry.lock, pyproject.toml, tests/test_examples.py, tests/test_notebooks.py, vsketch_cli/cli.py
- split away notebook testing in a separate file
- ignored that file
- added a note in examples/_notebooks
- fixed a typing error with cli
- updated deps
=> Removed dev dependency on Jupyter

.github/workflows/python-lint-tests.yml, README.md, docs/install.rst, poetry.lock, pyproject.toml, vsketch_cli/config_widget.py, vsketch_cli/gui.py, vsketch_cli/param_widget.py, vsketch_cli/seed_widget.py, vsketch_cli/sketch_viewer.py, vsketch_cli/threads.py
Following abey79/vpype#552
- pinned vpype to post-PySide6 commit
- simplified installation instructions and readme
- fixed installation instructions for dev setup
- added mesa stuff to CI
- updated deps
Fixes #292
=> Migrated to PySide6

docs/overview.rst, examples/random_seed/sketch_random_seed.py, tests/test_random.py, vsketch/vsketch.py
Allows the user to access the random seed once it has been set via `vsk.random_seed`.
=> expose random seed

vsketch/shape.py
Include options for `shape.BooleanOperation` in documentation. This does not describe what the various options do, this feature just lists them.
=> adding documentation for boolean operator

vsketch_cli/cli.py
When using `vsk run PATH` or `vsk save PATH`, PATH is allowed to be either a path to a regular file expected to contain Python source code of a sketch, or a path to a directory. If PATH refers to a directory, vsketch will search for a unique file within that directory matching `sketch_*.py`; if not present, it will search for a unique file matching `*.py`.
If neither are present, or there are ever multiple files matching the pattern, search fails.
This commit makes a small change to the search procedure to also search for a file named `sketch.py`. This permits using vsk with a directory structure like the following:
```
bezier_curve/sketch.py
bezier_curve/curves.py
```
Under the current behavior, `vsk run bezier_curve` would fail as there's no file matching `sketch_*.py`, and there isn't …
=> Change CLI sketch search process to use sketches named sketch.py

.github/workflows/release.yml, CHANGELOG.md, README.md, docs/install.rst, poetry.lock, pyproject.toml
Prepare for initial release and publication to PyPI.
=> Prepare for initial release

.readthedocs.yml
=> Fixed ReadTheDocs configuration file
