abey79/vsketch

tests/test_geometry.py, tests/utils.py, vsketch/vsketch.py
=> Fixed issue where `geometry()` would fail with empty polygons

.github/workflows/python-lint-tests.yml, poetry.lock, pyproject.toml
This PR:
- enabled python 3.9.1+
- removes support for python 3.6
- updates CI accordingly
Fixes #37
=> Add Python 3.9 compatibility

tests/test_random.py, vsketch/vsketch.py
=> Add grid_mode to noise()

docs/conf.py, docs/overview.rst, examples/bezier_bugs/sketch_bezier_bugs.py, examples/detail/sketch_detail.py, examples/noise_bezier/sketch_noise_bezier.py, examples/point_transform/sketch_point_transform.py, examples/polygons/sketch_polygons.py, examples/prime_circles/sketch_prime_circles.py, examples/quick_draw/sketch_quick_draw.py, examples/random_flower/sketch_random_flower.py, examples/random_lines/sketch_random_lines.py, examples/schotter/sketch_schotter.py, examples/shapely/sketch_shapely.py, examples/stroke_fill/sketch_stroke_fill.py, examples/subsketch/sketch_subsketch.py, examples/transforms/sketch_transforms.py, poetry.lock, pyproject.toml, vsketch/__init__.py, vsketch/sketch_class.py, vsketch/utils.py, vsketch/vsketch.py, vsketch_cli/cli.py, vsketch_cli/sketch_viewer.py, vsketch_cli/threads.py, vsketch_cli/utils.py
This PR introduces a new base class (`vsketch.SketchClass`) that must be sub-classed by user sketches (instead of `vsketch.Vsketch`). This is a major breaking change that will require modification to virtually every existing sketch.
New sketch template:
```python
import vsketch
class ExampleSketch(vsketch.SketchClass):
rect_size = vsketch.Param(5)
def draw(self, vsk: vsketch.Vsketch) -> None:
vsk.size("a5", landscape=True)
vsk.scale("cm")
vsk.rect(0, 0, self.rect_size, self.rect_size)
def finalize(self, vsk: vsketch.Vsketch) -> None:
vsk.vpype("linemerge linesimplify reloop linesort")
if __name__ == "__main__":
ExampleSketch()
```
There are two main reasons for this change:
1. Remove the namespace collision between `vsketch.Param` and `vksetch.Vsketch` API. For example, everyone wants a …
=> Sketch class refactoring (breaking change)

.github/workflows/python-lint-tests.yml, mypy.ini, poetry.lock, pyproject.toml, tests/test_examples.py, vsketch_cli/cli.py, vsketch_cli/config_widget.py, vsketch_cli/utils.py
- remove dependency to Typer, which is not (yet?) compatible with Click 8
- moved mypy conf to pyproject.toml and added missing type-xxx deps
- updated deps
- freeze dependency to vpype (currently 1.7.0) to avoid future install issues
- fixed isort config
- improved & simplified CI
Fixes #118
Fixes #119
=> Remove dependency to Typer

tests/test_geometry.py, vsketch/vsketch.py
Adds support and tests for `Point` and `MultiPoint` from Shapely.
=> Add Support for Shapely Point and MultiPoint

vsketch_cli/threads.py
I am running vsketch on Linux with Python 3.9 in a venv. I have an annoying issue where if there are any Python errors in the sketch Python file, vsketch simply freezes. It says "Loading..." in the window and prints the error to the console, but the window cannot be closed except by killing it and it no longer watches for changes.
This appears to be from `self._sketch_class.execute()` erroring and so it just sits and waits for the `completed` event to be emitted, but it is never emitted because the parent function crashes.
I have added a try/catch here that mitigates the issue. The window no longer freezes and now says "ERROR (see console)" as it is supposed to. Saving the file again causes it to update. The error is still printed to the console.
Thanks!
=> Catch, Show, and Continue on Errors in Sketch Thread

vsketch_cli/param_widget.py
When param.decimals is None, the input value is run
through math. log10, which fails for negative default values.
This just runs abs on the value before doing the log.
=> WIP - Fix negative float inputs

examples/quick_draw/config/a6_landscape.json, poetry.lock, pyproject.toml, vsketch/sketch_class.py, vsketch/vsketch.py, vsketch_cli/cli.py, vsketch_cli/threads.py
The `--param` option can now be used to override the value of a particular parameter. Single value, lists, range, and range with stride can be used for value. Multiple `--param` options can be used. This enables efficient exploration of the parameter space.
other changes:
- fixed multiple shapely 1.8 deprecation warnings
- added return value to SketchClass.set_value_with_validation() to indicate if value was successfully changed
- vpype pinned to a post-metadata revision
- fixed wrong `color_mode` for SVG export in multiple places
- updated dependency
- added config to quick_draw for demo purposes
- attempt to print path relative to cwd
- fixed SVG source string missing lots of options
=> Add `--param` to `vsk save` + misc

vsketch_cli/gui.py, vsketch_cli/sketch_viewer.py
Attempt at fixing an issue where the `vsk run` command hangs/continues running after the Qt window is closed.
I don't fully understand the fix, as I don't have much experience with Qt or asyncio, but I adopted some lines from various python Qt examples, and added an stop event to the file watcher.
=> Exit vsk run when Qt window is closed

examples/easing/sketch_easing.py
=> Fixed `easing` example to use `vsk.text()`

docs/overview.rst, vsketch_cli/sketch_viewer.py
I've added a couple shortcuts to save and randomize a sketch. I assigned the "S" shortcut to ~save~ like a drawing and "R" to randomize the seed, but I'm open to other options.
Also, I'm not quite sure if I should update the doc in some way.
=> add shortcuts to like and randomize

.github/workflows/python-lint-tests.yml, poetry.lock, pyproject.toml, vsketch/vsketch.py
- pinned snok/poetry-install to 1.3.1 for windows
- updated dependencies
=> Update dependencies and fix Windows workflow

vsketch_cli/utils.py
Modifies the path before executing a sketch script
Fixes #177
=> Modify path before executing sketch scripts

vsketch_cli/param_widget.py
Resolves #109 using @bcongdon's suggestion of `toPlainText()`. I couldn't find any tests that cover the viewer so I manually confirmed that both free text and `choices` type params live update and save/load correctly. Let me know if I'm just missing the tests.
=> use toPlainText() to retrieve value of text field

vsketch_cli/sketch_viewer.py, vsketch_cli/threads.py
Adds a feature to store the sketch parameters (and the seed! see #87) in the svg source tag when saving using the LIKE button. The format is designed to be the same what is found in config json files.
Sometimes I save things with a good set of parameters, but then I make a change to the sketch with a syntax error and loose my nice config.
=> Save sketch parameters in svg source tag on like

docs/install.rst
=> typo in example command

examples/_notebooks/bezier_bugs.ipynb, examples/_notebooks/detail.ipynb, examples/_notebooks/noise_bezier.ipynb, examples/_notebooks/polygons.ipynb, examples/_notebooks/prime_circles.ipynb, examples/_notebooks/quick_draw.ipynb, examples/_notebooks/random.ipynb, examples/_notebooks/shapely.ipynb, examples/_notebooks/stroke_fill.ipynb, examples/_notebooks/subsketch.ipynb, examples/_notebooks/transforms.ipynb
The examples in `examples/_notebooks` have `vsk.display(mode="matplotlib")` which is apparently an old / invalid argument (`matplotlib` seems to be the only supported mode now); this change removes them.
(I understand that running `vsketch` in notebooks is unsupported. Still I find it to be a really useful way to explore a new library, especially as a Python beginner.)
=> drop invalid mode="matplotlib" arg in notebooks

tests/test_circle.py, tests/test_line.py, tests/test_rect.py, tests/utils.py
Add a utility function to the test suite to test if the length of path drawn is equal to the expected length: `length_equal`
This was written to help show odd behavior of `vsk.circle` when the radius was negative https://github.com/abey79/vsketch/issues/352
In this PR the function `length_equal` is added and then used in existing tests where the length is known.
length_equal is written in the style of existing testing utility functions such as bounds_equal and uses np.close with rtol=1e-3. This means the paths will be considered to be the same length if the difference is within 0.001. This made sense to also use for this case because the calculated length is based on drawing a perfect circle with a circumference of diameter * pi, which is not exactly what is being drawn and even if it was …
=> add test for path length

vsketch/vsketch.py
Allows manipulation of 'svg_' properties directly within vsketch.
...
=> Set 'use_svg_metadata' to True in call to vpype.write_svg

vsketch_cli/cli.py, vsketch_cli/threads.py
Completes previous incomplete PR#380.  There were additional codepaths to vp.write_svg calls that I missed in the earlier PR.
...
=> Fix previous incomplete PR#380 regarding use_svg_metadata

vsketch/shape.py
Adds the ability for Shape.geometry() to accept a shapely MultiPoint object.  Per discussion on discord.
=> Updated Shape.geometry to accept MultiPoint objects.

docs/overview.rst, vsketch_cli/cli.py, vsketch_cli/gui.py, vsketch_cli/sketch_viewer.py
This commit adds the ability to configure the output SVG directory when using `vsk run`, via a new command-line option `--output-dir` (or, equivalently, the `VSK_OUTPUT_DIR` environment variable).
This provides more flexibility for users using vsketch as a library with multiple sketches, such as if a user wants to keep saved SVGs all in a common directory regardless of the directory structure of the plot source files themselves.
If no option is provided, retains the previous default behavior, which is to save the output in a directory called `output/` next to the sketch source file.
Tested using the following commands:
```bash
$ cd examples
$ vsk run noise_bezier/
$ ls noise_bezier/output/
noise_bezier_liked_1.svg
$ vsk run --output-dir=../my_output noise_bezier/
$ ls ../my_output/ …
```
=> Add CLI option to choose output directory for vsk run

tests/test_param.py, vsketch/sketch_class.py
`Param.set_value_with_validation` assigns a value to to a parameter, and checks that the value attempting to set is the right type. In addition, if the parameter has a defined min and/or max value, `set_value_with_validation` clamps the value to respect the defined bounds.
As an example, given a param defined with
`param = Param(0.0, min_value=-5.0, max_value=5.0)`, calling `param.set_value_with_validation(-10.0)` will result in the parameter value becoming -5.0, since that's the closest value that respects the `min_value` of `-5.0.
The logic that implements this behavior is implemented with:
```python
if self.min:
value = max(self.min, value)
if self.max:
value = min(self.max, value)
```
But this code does not have the expected behavior when either `self.min` or `self.max` are `0.0`. …
=> Fix bug in Param.set_value_with_validation when bounds are 0.0

docs/overview.rst
=> Small documentation typo fix.

vsketch/vsketch.py
Fix a few typos in the `size` pydoc.
=> Fix a few typos in the `size` pydoc

vsketch/sketch_class.py, vsketch/vsketch.py
* Fixes #416
* Related to #205
Before:
<br/>
<br/>
After:
=> Properly display and export the pen widths set by the sketch
